var documenterSearchIndex = {"docs": [

{
    "location": "#",
    "page": "Readme",
    "title": "Readme",
    "category": "page",
    "text": ""
},

{
    "location": "#SafeTestsets.jl-1",
    "page": "Readme",
    "title": "SafeTestsets.jl",
    "category": "section",
    "text": "(Image: Build Status) (Image: Build status) (Image: codecov)@safetestset puts @testset into a module.You can use it byusing SafeTestsets\n@safetestset \"Benchmark Tests\" begin include(\"benchmark_tests.jl\") endwhich makes a new module whose name is generated by gensym(), orusing SafeTestsets\n@safetestset BenchmarkTests = \"Benchmark Tests\" begin include(\"benchmark_tests.jl\") endwhich makes a module named BenchmarkTests."
},

{
    "location": "autodocs/#",
    "page": "Docstrings",
    "title": "Docstrings",
    "category": "page",
    "text": "SafeTestsets.@safetestsetSafeTestsets.SafeTestsetsSafeTestsets.errSafeTestsets.evalSafeTestsets.include"
},

]}
