var documenterSearchIndex = {"docs": [

{
    "location": "#",
    "page": "Readme",
    "title": "Readme",
    "category": "page",
    "text": ""
},

{
    "location": "#ReinforcementLearningEnvironmentGym-1",
    "page": "Readme",
    "title": "ReinforcementLearningEnvironmentGym",
    "category": "section",
    "text": "(Image: Build Status)(Image: Coverage Status)(Image: codecov.io)Making the OpenAI gym environments available to the Julia Reinforcement Learning package."
},

{
    "location": "autodocs/#",
    "page": "Docstrings",
    "title": "Docstrings",
    "category": "page",
    "text": "ReinforcementLearningEnvironmentGym.AccumulatingTracesReinforcementLearningEnvironmentGym.ActorCriticPolicyGradientReinforcementLearningEnvironmentGym.AllRewardsReinforcementLearningEnvironmentGym.ConstantNumberEpisodesReinforcementLearningEnvironmentGym.ConstantNumberStepsReinforcementLearningEnvironmentGym.CriticReinforcementLearningEnvironmentGym.DQNReinforcementLearningEnvironmentGym.DeepActorCriticReinforcementLearningEnvironmentGym.EpisodeReinforcementLearningEnvironmentGym.EpisodicReinforceReinforcementLearningEnvironmentGym.EpsilonGreedyPolicyReinforcementLearningEnvironmentGym.EvaluateGreedyReinforcementLearningEnvironmentGym.EvaluationPerEpisodeReinforcementLearningEnvironmentGym.EvaluationPerTReinforcementLearningEnvironmentGym.ExpectedSarsaReinforcementLearningEnvironmentGym.ForcedEpisodeReinforcementLearningEnvironmentGym.ForcedPolicyReinforcementLearningEnvironmentGym.GymEnvReinforcementLearningEnvironmentGym.ImageCropReinforcementLearningEnvironmentGym.ImagePreprocessorReinforcementLearningEnvironmentGym.ImageResizeBilinearReinforcementLearningEnvironmentGym.ImageResizeNearestNeighbourReinforcementLearningEnvironmentGym.LinearReinforcementLearningEnvironmentGym.LinearDecreaseEpsilonReinforcementLearningEnvironmentGym.MDPLearnerReinforcementLearningEnvironmentGym.MeanRewardReinforcementLearningEnvironmentGym.MonteCarloReinforcementLearningEnvironmentGym.NoBiasCorrectorReinforcementLearningEnvironmentGym.NoPreprocessorReinforcementLearningEnvironmentGym.NoTracesReinforcementLearningEnvironmentGym.PolicyGradientBackwardReinforcementLearningEnvironmentGym.ProgressReinforcementLearningEnvironmentGym.QLearningReinforcementLearningEnvironmentGym.RLSetupReinforcementLearningEnvironmentGym.RadialBasisFunctionsReinforcementLearningEnvironmentGym.RandomProjectionReinforcementLearningEnvironmentGym.RecordAllReinforcementLearningEnvironmentGym.ReduceEpsilonPerEpisodeReinforcementLearningEnvironmentGym.ReduceEpsilonPerTReinforcementLearningEnvironmentGym.ReinforcementLearningReinforcementLearningEnvironmentGym.ReinforcementLearningEnvironmentGymReinforcementLearningEnvironmentGym.ReplacingTracesReinforcementLearningEnvironmentGym.RewardLowpassFilterBiasCorrectorReinforcementLearningEnvironmentGym.SarsaReinforcementLearningEnvironmentGym.SaveLearnerReinforcementLearningEnvironmentGym.SmallBackupsReinforcementLearningEnvironmentGym.SoftmaxPolicyReinforcementLearningEnvironmentGym.SparseRandomProjectionReinforcementLearningEnvironmentGym.StateAggregatorReinforcementLearningEnvironmentGym.StepReinforcementLearningEnvironmentGym.TilingStateAggregatorReinforcementLearningEnvironmentGym.TimeStepsReinforcementLearningEnvironmentGym.TotalRewardReinforcementLearningEnvironmentGym.VisualizeReinforcementLearningEnvironmentGym.__init__ReinforcementLearningEnvironmentGym.compareReinforcementLearningEnvironmentGym.evalReinforcementLearningEnvironmentGym.getspaceReinforcementLearningEnvironmentGym.getvalueReinforcementLearningEnvironmentGym.getvaluesReinforcementLearningEnvironmentGym.gymReinforcementLearningEnvironmentGym.huberlossReinforcementLearningEnvironmentGym.includeReinforcementLearningEnvironmentGym.interactgym!ReinforcementLearningEnvironmentGym.learn!ReinforcementLearningEnvironmentGym.listallenvsReinforcementLearningEnvironmentGym.plotcomparisonReinforcementLearningEnvironmentGym.policy_iteration!ReinforcementLearningEnvironmentGym.run!ReinforcementLearningEnvironmentGym.togpuReinforcementLearningEnvironmentGym.value_iteration!"
},

]}
