var documenterSearchIndex = {"docs": [

{
    "location": "#",
    "page": "Readme",
    "title": "Readme",
    "category": "page",
    "text": ""
},

{
    "location": "#ApproximateComputations.jl-1",
    "page": "Readme",
    "title": "ApproximateComputations.jl",
    "category": "section",
    "text": "(Image: Build Status)(Image: codecov)Interactive Documentation HereApproximateComputations.jl is a library for the automatic applicaiton approximate computation software techniques to existing code. In this context, software approximation is where we perform some transformation to existing code to reduce the accuracy for gain in performance.This is usually applied through function replacement. The standard workflow is to determine the maximum or average acceptable error for a given code block and then reducing the accuracy of the function so that as little work as possible is spent on gaining a more acurate result that the acceptable level."
},

{
    "location": "autodocs/#",
    "page": "Docstrings",
    "title": "Docstrings",
    "category": "page",
    "text": "ApproximateComputations.@BuildOverrideFromArrayApproximateComputations.ApproximateComputationsApproximateComputations.ApproximateHashingMemoiseApproximateComputations.ApproximationApproximateComputations.BuildOverrideFromArrayApproximateComputations.ClearSymbolDictApproximateComputations.ClipFrontAndBackApproximateComputations.CreateDataFrameRowApproximateComputations.EmulateTreeApproximateComputations.ErrorResultsContainerApproximateComputations.EvaluateForLoopApproximateComputations.FilterFunctionListApproximateComputations.FullUnwrapApproximateComputations.GenerateAllApproximationFunctionsApproximateComputations.GeneratedFunctionTypeApproximateComputations.GetApproximateComputations.GetAbsoluteErrorApproximateComputations.GetAllLeavesApproximateComputations.GetAllLeavesListApproximateComputations.GetAllSymbolsApproximateComputations.GetAllSymbolsListApproximateComputations.GetAllTreesApproximateComputations.GetApproximatePateFunctionApproximateComputations.GetApproximatePateFunction_EvalApproximateComputations.GetApproximatePolyFunctionApproximateComputations.GetApproximatePolyFunction_EvalApproximateComputations.GetConstructionFunctionApproximateComputations.GetErrorDataForFunctionApproximateComputations.GetErrorInTreeApproximateComputations.GetFastestAcceptableApproximateComputations.GetFunctionNameApproximateComputations.GetGlobalIDApproximateComputations.GetMeanBenchmarkTimeApproximateComputations.GetMeanDifferenceApproximateComputations.GetMedianBenchmarkTimeApproximateComputations.GetMedianDifferenceApproximateComputations.GetOperatorIDsApproximateComputations.GetOperatorsApproximateComputations.GetOverrideFunctionListApproximateComputations.GetOverridesApproximateComputations.GetResultForIDApproximateComputations.GetSubTreeApproximateComputations.HasIdApproximateComputations.InArrayApproximateComputations.LoopPerforationApproximateComputations.OnlyEvenIterationsApproximateComputations.OnlyFirstHalfApproximateComputations.OnlyOddIterationsApproximateComputations.OnlySecondHalfApproximateComputations.OperatorApproximateComputations.PadArrayApproximateComputations.PlotASTErrorApproximateComputations.PlotApproximationFunctionDiffApproximateComputations.PlotApproximationFunctionDiffHistApproximateComputations.PlotApproximationFunctionResultsApproximateComputations.PlotMedianErrorApproximateComputations.PlotMedianRuntimeApproximateComputations.PlotRuntimeErrorPairApproximateComputations.PrintTreeComparisonErrorApproximateComputations.ReplaceAllVariablesOfTypeApproximateComputations.ReplaceConstantsWithVariablesApproximateComputations.ReplaceSubTreeApproximateComputations.ReplaceTypeOfSpecifiedVariableApproximateComputations.ResetGlobalIDApproximateComputations.SetResultForIDApproximateComputations.SetSymbolValueApproximateComputations.SymbolDictApproximateComputations.TestFunctionApproximateComputations.ToStringApproximateComputations.TreeComparisonApproximateComputations.TreeMemberApproximateComputations.TreeToFunctionApproximateComputations.TreeToFunctionLeafApproximateComputations.TrendingMemoisationApproximateComputations.UnwrapTreeApproximateComputations.UpdateEnvironmentForFunctionApproximateComputations.VariableApproximateComputations.WrapTreeApproximateComputations.evalApproximateComputations.g_IDApproximateComputations.greetApproximateComputations.includeApproximateComputations.pateLinearRationalFitApproximateComputations.polyfitApproximateComputations.printtree"
},

]}
