var documenterSearchIndex = {"docs": [

{
    "location": "#",
    "page": "Readme",
    "title": "Readme",
    "category": "page",
    "text": ""
},

{
    "location": "#LanguageServer-1",
    "page": "Readme",
    "title": "LanguageServer",
    "category": "section",
    "text": "(Image: Project Status: Active - The project has reached a stable, usable state and is being actively developed.) (Image: Build Status) (Image: Build status) (Image: LanguageServer) (Image: codecov.io)"
},

{
    "location": "#Overview-1",
    "page": "Readme",
    "title": "Overview",
    "category": "section",
    "text": "This package implements the Microsoft Language Server Protocol for the Julia programming language.Text editors with a client for the Language Server Protocol are able to make use of the Julia Language Server for various code editing features:VS Code\nAtom\nVim and Neovim\nEmacs\nSublime Text"
},

{
    "location": "autodocs/#LanguageServer.URI2",
    "page": "Docstrings",
    "title": "LanguageServer.URI2",
    "category": "type",
    "text": "A type that represents a URI. The main feature provided currently is that when the file:// scheme is used and the platform is Windows, equality and hashing is case-insensitive.\n\n\n\n\n\n"
},

{
    "location": "autodocs/#",
    "page": "Docstrings",
    "title": "Docstrings",
    "category": "page",
    "text": "LanguageServer.@json_readLanguageServer.ApplyWorkspaceEditParamsLanguageServer.ApplyWorkspaceEditResponseLanguageServer.CancelParamsLanguageServer.CapabilitiesLanguageServer.ClientCapabilitiesLanguageServer.CodeActionCapabilitiesLanguageServer.CodeActionContextLanguageServer.CodeActionKindCapabilitiesLanguageServer.CodeActionLiteralCapabilitiesLanguageServer.CodeActionParamsLanguageServer.CodeLensLanguageServer.CodeLensOptionsLanguageServer.CodeLensParamsLanguageServer.CodeLensRegistrationOptionsLanguageServer.CommandLanguageServer.CompletionCapabilitiesLanguageServer.CompletionContextLanguageServer.CompletionItemLanguageServer.CompletionItemCapabilitiesLanguageServer.CompletionItemKindLanguageServer.CompletionItemKindCapabilitiesLanguageServer.CompletionListLanguageServer.CompletionOptionsLanguageServer.CompletionParamsLanguageServer.CompletionTriggerKindLanguageServer.ConfigurationItemLanguageServer.ConfigurationParamsLanguageServer.DefaultTypeConstructorLocLanguageServer.DiagnosticLanguageServer.DiagnosticRelatedInformationLanguageServer.DiagnosticSeverityLanguageServer.DidChangeConfigurationLanguageServer.DidChangeTextDocumentParamsLanguageServer.DidChangeWatchedFilesParamsLanguageServer.DidChangeWatchedFilesRegistrationOptionsLanguageServer.DidCloseTextDocumentParamsLanguageServer.DidOpenTextDocumentParamsLanguageServer.DidSaveTextDocumentParamsLanguageServer.DocumentLanguageServer.DocumentFilterLanguageServer.DocumentFormattingParamsLanguageServer.DocumentHighlightLanguageServer.DocumentHighlightKindLanguageServer.DocumentLinkLanguageServer.DocumentLinkOptionsLanguageServer.DocumentLinkParamsLanguageServer.DocumentOnTypeFormattingOptionsLanguageServer.DocumentOnTypeFormattingParamsLanguageServer.DocumentOnTypeFormattingRegistrationOptionsLanguageServer.DocumentRangeFormattingParamsLanguageServer.DocumentSelectorLanguageServer.DocumentSymbolCapabilitiesLanguageServer.DocumentSymbolParamsLanguageServer.DocumentUriLanguageServer.ExecuteCommandOptionsLanguageServer.ExecuteCommandParamsLanguageServer.ExecuteCommandRegistrationOptionsLanguageServer.FileChangeTypeLanguageServer.FileChangeType_ChangedLanguageServer.FileChangeType_CreatedLanguageServer.FileChangeType_DeletedLanguageServer.FileEventLanguageServer.FileSystemWatcherLanguageServer.FormattingOptionsLanguageServer.HoverLanguageServer.HoverCapabilitiesLanguageServer.InitializeParamsLanguageServer.InitializeResultLanguageServer.InvokedLanguageServer.JSONRPCLanguageServer.LSDiagnosticLanguageServer.LanguageServerLanguageServer.LanguageServerInstanceLanguageServer.LocationLanguageServer.LogMessageParamsLanguageServer.MarkedStringLanguageServer.MarkupContentLanguageServer.MessageLanguageServer.MessageActionItemLanguageServer.MessageTypeLanguageServer.ParameterInformationLanguageServer.PositionLanguageServer.PublishDiagnosticsCapabilitiesLanguageServer.PublishDiagnosticsParamsLanguageServer.RangeLanguageServer.ReferenceContextLanguageServer.ReferenceParamsLanguageServer.RegistrationLanguageServer.RegistrationParamsLanguageServer.RenameParamsLanguageServer.SaveOptionsLanguageServer.ServerCapabilitiesLanguageServer.ShowMessageParamsLanguageServer.ShowMessageRequestParamsLanguageServer.SignatureCapabilitiesLanguageServer.SignatureHelpLanguageServer.SignatureHelpOptionsLanguageServer.SignatureHelpRegistrationOptionsLanguageServer.SignatureInformationLanguageServer.SignatureInformationCapabilitiesLanguageServer.StaticRegistrationOptionsLanguageServer.SymbolCapabilitiesLanguageServer.SymbolInformationLanguageServer.SymbolKindLanguageServer.SymbolKindCapabilitiesLanguageServer.SynchronizationCapabilitiesLanguageServer.TLanguageServer.TextDocumentChangeRegistrationOptionsLanguageServer.TextDocumentClientCapabilitiesLanguageServer.TextDocumentContentChangeEventLanguageServer.TextDocumentEditLanguageServer.TextDocumentIdentifierLanguageServer.TextDocumentItemLanguageServer.TextDocumentPositionParamsLanguageServer.TextDocumentReasonLanguageServer.TextDocumentRegistrationOptionsLanguageServer.TextDocumentSyncKindLanguageServer.TextDocumentSyncOptionsLanguageServer.TextEditLanguageServer.TriggerCharacterLanguageServer.TriggerForIncompleteCompletionLanguageServer.URI2LanguageServer.UnregistrationLanguageServer.UnregistrationParamsLanguageServer.VersionedTextDocumentIdentifierLanguageServer.WatchKindLanguageServer.WillSaveTextDocumentParamsLanguageServer.WorkspaceClientCapabilitiesLanguageServer.WorkspaceEditLanguageServer.WorkspaceEditCapabilitiesLanguageServer.WorkspaceFolderLanguageServer.WorkspaceFoldersChangeEventLanguageServer.WorkspaceFoldersOptionsLanguageServer.WorkspaceOptionsLanguageServer.WorkspaceSymbolParamsLanguageServer._offset_unitrangeLanguageServer.clear_diagnosticsLanguageServer.convert_diagnosticLanguageServer.didChangeWorkspaceFoldersParamsLanguageServer.evalLanguageServer.filepath2uriLanguageServer.find_refLanguageServer.find_referencesLanguageServer.find_rootLanguageServer.get_line_offsetsLanguageServer.get_locationsLanguageServer.get_offsetLanguageServer.get_open_in_editorLanguageServer.get_partial_completionLanguageServer.get_position_atLanguageServer.get_sig_argsLanguageServer.get_signaturesLanguageServer.get_textLanguageServer.get_toksLanguageServer.haskeynotnullLanguageServer.hasreadpermLanguageServer.includeLanguageServer.is_ignoredLanguageServer.is_workspace_fileLanguageServer.isjuliabasedirLanguageServer.iter_linesLanguageServer.joinuriwithpathLanguageServer.kw_completionLanguageServer.latex_completionsLanguageServer.load_folderLanguageServer.load_rootpathLanguageServer.parse_allLanguageServer.parse_jmdLanguageServer.processLanguageServer.publish_diagnosticsLanguageServer.read_transport_layerLanguageServer.remove_workspace_filesLanguageServer.sendLanguageServer.serverCapabilitiesLanguageServer.serverbusyLanguageServer.serverreadyLanguageServer.set_open_in_editorLanguageServer.should_file_be_lintedLanguageServer.str_valueLanguageServer.toggle_file_lintLanguageServer.updateLanguageServer.uri2filepathLanguageServer.write_transport_layer"
},

]}
